### ISSUE TITLE
학교 로고 타이틀이 로그인 상태에도 Login으로 표시됨

### ISSUE THREAD

**Issue by egwkim** [RODELA5/activity-time-tracking-system#5]
학교 로고 타이틀이 로그인 상태에도 Login으로 표시됨
 - Logout으로 수정하기

이미지 alt 속성이 ...으로 되어있는데 이것도 함께 수정하면 좋을 듯 (삭제하거나 수정하기)

**Comment by egwkim** [comment]
<img src="https://user-images.githubusercontent.com/35051914/173231365-24814338-1048-4357-afec-7ca2031fdc62.png" width="70%">

**Comment by HURDOO** [comment]
0717eb9 내용 한번 바꿔보았는데 어떤가요?

![image](https://user-images.githubusercontent.com/64835865/179363105-d136cc05-0a9b-4ca3-aa66-2ecd7f5cd0e7.png)

**Comment by egwkim** [comment]
👍👍
